### ISSUE TITLE
Tests fails on OS X 10.9

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-swift#1]
Hi! Can we test this in travis, is that feasible?

**Comment by dethi** [comment]
Yes, of course. I will write the travis.yml file.

**Comment by redox** [comment]
I'm sending you some credentials to encrypt in the travis.yml file

**Comment by dethi** [comment]
I added the travis.yml file, but I had a issue with travis. Travis uses OS X 10.9. So I have try to compile the framework on a clean VM of OS X 10.10 : no problem, and on a clean VM of OS X 10.9 : the framework compiles correctly but the unit tests never start. I get a linked error.
I haven't find my error in the target's configuration, so if someone has an idea..

**Comment by dethi** [comment]
After a lot of investigation, I finally found the error: Alamofire. The project targets OS X 10.10.
After modifying their settings, our tests starts. However Alamofire has an issue when decoding JSON. I will report the issue soon.

**Comment by redox** [comment]
\o/

**Comment by dethi** [comment]
Fixed in 1.1.0
