### ISSUE TITLE
tvOS not supported in pod file

### ISSUE THREAD

**Issue by azzoor** [algolia/algoliasearch-client-swift#117]
I've added the pod to my pod file and when I try to do a pod install I get the following error message in terminal.

[!] The platform of the target `AppName-tvOS` (tvOS 9.0) is not compatible with `AlgoliaSearch-Client-Swift (3.3)`, which does not support `tvos`.

**Comment by clement-leprovost** [comment]
Yes, thanks for reporting it, but this is a known issue. PR #113 fixes it and has already been merged to master. The release will come soon (= this week). :)

**Comment by clement-leprovost** [comment]
Version [3.6](https://github.com/algolia/algoliasearch-client-swift/releases/tag/3.6) has been released, which fixes this issue.

**Comment by azzoor** [comment]
I'm still having issues with this. I got the pod 'AlgoliaSearch-Client-Swift', '~> 3.6' to work but when I try objective-c pod 'AlgoliaSearch-Client', '~> 3.6' on my tvOS project I get the error, 

[!] The platform of the target `AppName` (tvOS 9.0) is not compatible with `AlgoliaSearch-Client (3.7.0)`, which does not support `tvos`.

**Comment by clement-leprovost** [comment]
@azzoor Sure, `AlgoliaSearch-Client` refers to our **now deprecated** legacy [Objective-C client](https://github.com/algolia/algoliasearch-client-objc/). But you should be able to use `AlgoliaSearch-Client-Swift` from Objective-C without any problem. If your Objective-C code is still targeting the legacy client, however, you might be interested in reading the [Migration Guide](https://github.com/algolia/algoliasearch-client-swift/wiki/Migration-guide-from-Objective-C-to-Swift-API-Client).
