### ISSUE TITLE
watchOS

### ISSUE THREAD

**Issue by JonathanBouaziz** [algolia/algoliasearch-client-swift#118]
Hi!
Is there any reason why your library couldn't work on watchOS?

**Comment by clement-leprovost** [comment]
Honestly, I don't know. We haven't investigated watchOS yet. I guess it *could* work if watchOS is sufficiently in line with the other OSes.

The question is more: is there a use case? @JonathanBouaziz Do you have an example?

**Comment by JonathanBouaziz** [comment]
Well with all the new iOS extensions, I need to create a framework that will contain all the necessary classes to get something up and running quickly. I have an iOS, tvOS and watchOS target. Your SDK is part of it but since it doesn't support watchOS in the podspec I'm getting an error.

**Comment by clement-leprovost** [comment]
All right, we'll see what we can do. => Tagging this as "enhancement".
