### ISSUE TITLE
X-Algolia-QueryParameters is missing

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-swift#12]
We can set the `X-Algolia-TagFilters` and the `X-Algolia-UserToken` header, but the new `X-Algolia-QueryParameters` is missing.

We could probably create something like:

```
let client = AlgoliaSearch.Client(appID: "xxxxxxx", apiKey: "xxxxxxxxxxxxx", queryParameters:"tagFilters=xxxxxxxx")
```

**Comment by dethi** [comment]
Can you explain me the purpose of `X-Algolia-QueryParameters`?

For now, it can be set with:

```swift
client.setExtraHeader("tagFilters=xxxxx", forKey: "X-Algolia-QueryParameters")
```

**Comment by redox** [comment]
Yes, basically we've improved our "secured headers" and we're not only allowing to generate a Secured API Key restricting the search on tagFilters, but on any other query parameters. So I could write:

```ruby
public_key = Algolia.generate_secured_api_key('SearchOnlyAPIKeyKeptPrivate', 'numericFilters=user_id%3d42') # URLEncode(user_id=42)
```

and then in Swift I would do:

```swift
let client = AlgoliaSearch.Client(appID: "xxxxxxx", apiKey: "my generated public_key", queryParameters:"numericFilters=user_id%3d42'")
```

**Comment by dethi** [comment]
What happen if QueryParameters and TagFilters are set?

**Comment by redox** [comment]
They are merged at the API-level, but we recommend/document using QueryParameters now, the previous TagFilters is kind of deprecated.

**Comment by dethi** [comment]
Same for UserToken?

**Comment by redox** [comment]
@Nagriar this one is kept, right?
