### ISSUE TITLE
Setting the X-Algolia-TagFilters seems to generate a 403 in the swift2 branch

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-swift#13]
Seems to work on `master`.

**Comment by dethi** [comment]
Hum.. Have you the log of the request (server side) ?

**Comment by redox** [comment]
Yes, here it is:

```
Host: ***********-dsn.algolia.net
Content-Type: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
X-Algolia-API-Key: bd8*************************************************************
X-Algolia-TagFilters: 55e5******************
Accept: */*
User-Agent: Algolia for Swift 1.4.2
X-Algolia-Application-Id: ************
Content-Length: 23
Accept-Language: en-us
```

It seems the exact same key + same tagFilters (except used with X-Algolia-QueryParameters) is working in JavaScript.

**Comment by dethi** [comment]
Are there any special characters in the TagFilters? It's maybe an encoding error.

**Comment by redox** [comment]
No, seems OK :/

**Comment by stephanejais** [comment]
I've built AlgoliaSearch.framework from master with Xcode 6 and tried to use it with my Swift 2 project under Xcode 7 beta.

It results in the same 403 error, which means the issue is probably due to a change in the behaviour of iOS rather than the port to Swift 2.

**Comment by dethi** [comment]
Does it work if you use X-Algolia-QueryParameters instead of X-Algolia-TagFilters?

```swift
client.setExtraHeader("tagFilters=xxxxx", forKey: "X-Algolia-QueryParameters")
```

**Comment by stephanejais** [comment]
Not with the swift2 branch.

Here's my code:

        let client = AlgoliaSearch.Client(appID: "xxx", apiKey: "xxx")
        client.setExtraHeader("tagFilters=xxx", forKey: "X-Algolia-QueryParameters")
        let index = client.getIndex("xxx")
        index.search(Query(query:"kate"), block:{result, error in
            print(result, error)
        })

And the output:

    nil Optional(Error Domain=Invalid Application-ID or API key Code=403 "(null)")

**Comment by clement-leprovost-algolia** [comment]
Maybe a manifestation of #27.
