### ISSUE TITLE
Can't import in Vc - Cannot import module being compiled

### ISSUE THREAD

**Issue by grantkemp** [algolia/algoliasearch-client-swift#16]
I have tried installing via Cocapods and get the following error when trying to import Algolia. 
Any ideas how to get it working? 

Have tried cleaning the project. 

Here is the Pod file: 
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Algolia' do
pod 'AlgoliaSearch-Client-Swift', '~> 1.4'
end

```

**Comment by grantkemp** [comment]
ah i- it looks like the latest Swift library doesn't work in latest Xcode and Swift 2. Any idea for when its going to be updated? 


<img width="258" alt="screen shot 2015-10-14 at 12 19 21" src="https://cloud.githubusercontent.com/assets/751115/10482160/e7d462f6-726d-11e5-965a-f583ef8a07b3.png">

**Comment by redox** [comment]
Hmmm, can you confirm you're using the latest 2.0 version of our API client?

**Comment by grantkemp** [comment]
Hiya, I am using the version in your docs.. 
Will see if I can get an updated version

**Comment by redox** [comment]
> Hiya, I am using the version in your docs..

Oh, and I see the README of the github project is not updated, promoting `1.4` instead of `2.0`. Fixing it now!

**Comment by grantkemp** [comment]
Yep - Thanks! .. will keep trying it.

**Comment by redox** [comment]
> Yep - Thanks! .. will keep trying it.

Cool, let us know how it goes :)
