### ISSUE TITLE
Cancel a search request

### ISSUE THREAD

**Issue by sts2055** [algolia/algoliasearch-client-swift#18]
Hi there,

Is there a way to cancel requests?
I could only find the following internal method in the Client:

```
/// Cancel a queries. Only the last ten queries can be cancelled.
    func cancelQueries(method: HTTPMethod, path: String) {
        for request in requestBuffer {
            if request.request.URL!.path! == path {
                if request.request.HTTPMethod == method.rawValue {
                    request.cancel()
                }
            }
        }
    }

```

Is there or are there plans to implement public methods for cancelling requests?

Thank you for your help.

**Comment by dethi** [comment]
Hi,
Well, I can make this one public if you want. But it will be able to cancel only the last 10 queries.
Do you need more?

**Comment by sts2055** [comment]
Hi @dethi,

Awesome, no that would work perfectly. 

I noticed that the path parameter requires endpoints that are defined internally: e.g

```
public func multipleQueries(queries: [AnyObject], block: CompletionHandler? = nil) {
        let path = "1/indexes/*/queries"
```

Would it be a pain to implement the public method in a way to say: Cancel all previous X requests without specifying method and path? Or say: Cancel the previous multipleQueries request?

**Comment by dethi** [comment]
I will do it Thursday, with an enum to choose the type of operation to cancel. Is it ok for you?

**Comment by sts2055** [comment]
Perfect, thank you so much!



--
Stefan

**Comment by dethi** [comment]
Hi @sts2055 
I just found that we have already a public method to cancel all the previous search, `index.cancelPreviousSearch()`. Is it sufficient for you?

**Comment by sts2055** [comment]
Hi @dethi, thank you for your response.

Looks like that function would work great for me.

The Index class' initialiser is currently internal:
```
init(client: Client, indexName: String) {
        self.client = client
        self.indexName = indexName
        urlEncodedIndexName = indexName.urlEncode()
    }
```

I can't use this initialiser because it isn't public. 

I have been searching for another way to instantiate the Index class, but couldn't find one.

**Comment by dethi** [comment]
https://github.com/algolia/algoliasearch-client-swift/blob/master/Source/Client.swift#L229-L234 :)

**Comment by sts2055** [comment]
Thank you for your help!

**Comment by tamimattafi** [comment]
@dethi Links not working, is there anyway to achieve the same for android, please ?

**Comment by dethi** [comment]
Hi @tamimattafi, I'm not working for Algolia anymore, but my former colleagues can probably guide you.
cc @redox to ping the current project owner

**Comment by redox** [comment]
> @dethi Links not working, is there anyway to achieve the same for android, please ?
> cc @redox to ping the current project owner

@PLNech  & @q-litzler  are definitely the right people to talk to!

**Comment by q-litzler** [comment]
Hello @tamimattafi,

Every request from the Android client can be cancelled by calling `cancel` on its individual reference. Is this what you were looking for ?

Please note that the Android client is now in maintenance mode. This means that we no longer add feature to it, and only fix critical bugs.

We now recommend using the Kotlin client for Android development instead.

https://github.com/algolia/algoliasearch-client-kotlin

**Comment by tamimattafi** [comment]
Hello @q-litzler, Thank you for your response

I'm considering switching to the Kotlin client but the Kotlin client requires using one of ktor's libraries, but they all have some duplicated classes the prevent the IDE from compiling , is there a fix for this?

Also, my Algolia search query using the android-client isn't returning an exact result.
For example, writing the word TOTAL returns a query of 23 items, while using the  search field on the web browser returns 49.

**Comment by q-litzler** [comment]
Can you share the exact error message for the ktor library ?

**Comment by q-litzler** [comment]
@tamimattafi can you please open an issue on https://github.com/algolia/algoliasearch-client-kotlin

**Comment by tamimattafi** [comment]
@q-litzler I will switch to kotlin client during these 2 days, I will start an issue if needed.

**Comment by tamimattafi** [comment]
@q-litzler I have added ktor dependency just for a simple compiling test

_result is the following :_
gradle sync : **Success**
project build/compile : **Failure** 
Log : `More than one file was found with OS independent path 'META-INF/kotlinx-io.kotlin_module'`

- excluding these classes from packaging in the gradle.build file shows more and more other duplicated classes.

- navigating to the project libraries directory, exactly to ktor's one shows that all classes have a duplication or more.

_used versions :_ 
android studio : `3.4.1`
kotlin : `1.3.41`
gradle : `default gradle wrapper`
ktor : `"io.ktor:ktor-client-android:1.2.2"`

**Comment by q-litzler** [comment]
Hello,

While I try to find a more proper solution to this, here is the complete list of files that you need to exclude:

```
    packagingOptions {
        exclude("META-INF/kotlinx-serialization-runtime.kotlin_module")
        exclude("META-INF/kotlinx-coroutines-core.kotlin_module")
        exclude("META-INF/ktor-http.kotlin_module")
        exclude("META-INF/kotlinx-io.kotlin_module")
        exclude("META-INF/atomicfu.kotlin_module")
        exclude("META-INF/ktor-utils.kotlin_module")
        exclude("META-INF/kotlinx-coroutines-io.kotlin_module")
        exclude("META-INF/ktor-client-json.kotlin_module")
        exclude("META-INF/ktor-client-json.kotlin_module")
        exclude("META-INF/ktor-client-logging.kotlin_module")
        exclude("META-INF/algoliasearch-client-kotlin.kotlin_module")
        exclude("META-INF/ktor-client-core.kotlin_module")
        exclude("META-INF/ktor-client-serialization.kotlin_module")
        exclude("META-INF/ktor-http-cio.kotlin_module")
    }
```

Let me know if this helps.
