### ISSUE TITLE
deleteByQuery is missing

### ISSUE THREAD

**Issue by dethi** [algolia/algoliasearch-client-swift#2]

**Comment by seafoox** [comment]
Please make sure that in the case the distinct is enabled on the index (with distinct > 1), we  `distinct=false` at query time, so the number of hits won't be > 1000. Otherwise, it will returns the following error: 

```
{
  "message": "invalid distinct value, hitsPerPage * distinct should be <= 1000",
  "status": 400
}
```

**Comment by clement-leprovost-algolia** [comment]
Available in the `v3` branch, waiting for release.
