### ISSUE TITLE
The tutorials seem to refer to web projects

### ISSUE THREAD

**Issue by grantkemp** [algolia/algoliasearch-client-swift#20]
The tutorials in the documentation refer to web projects not IOS.  is there a link to IOS projects?

**Comment by dethi** [comment]
Hello,
Yes there is one tutorial, https://www.algolia.com/doc/tutorials/ios-instant-search
The source code is available here: https://github.com/algolia/algolia-swift-demo
:)

**Comment by grantkemp** [comment]
Ah found it.  you should update in the Readme for this. I will have a go on it. I recall starting it ages ago.
