### ISSUE TITLE
Ensure keep alive is working

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-swift#22]

**Comment by dethi** [comment]
@redox Sufficient? Or you mean a more complex test?

```
Host: ********-dsn.algolia.net
Connection: keep-alive
X-Algolia-API-Key: ********************************
Accept: */*
User-Agent: Algolia for Swift 2.1.0
X-Algolia-Application-Id: **********
Accept-Language: en-us
Accept-Encoding: gzip, deflate
```

**Comment by redox** [comment]
Maybe we need programmatic tests because we cannot ensure we're not opening a new (keep-alive) connection at each query. We could test if the elapsed time of the first request is bigger than the average of the next 5 ones?
