### ISSUE TITLE
Error while running on device.

### ISSUE THREAD

**Issue by proactive-solutions** [algolia/algoliasearch-client-swift#290]
I am getting the error **"type named 'CompletionHandler' in module 'AlgoliaSearch'"**, while running on device. working fine on simulator.

![screen shot 2017-01-25 at 6 39 23 pm](https://cloud.githubusercontent.com/assets/13619716/22291714/c91b5fa4-e32d-11e6-8020-cfc743fc6eb5.png)

**Comment by clement-leprovost** [comment]
@proactive-solutions Judging by your screenshot, it looks more like a build error than a runtime error. (And the device is set to "Generic iOS Device", which is a build-only device, so you wouldn't be able to run the code in this configuration anyway.)

First of all, Xcode is sometimes a capricious tool, so maybe you can first try to clean the project, and clean Xcode's derived data if a regular clean doesn't work.

Then, apparently, the AlgoliaSearch module can be found, but not the types defined in it. This is weird, but maybe indicates that your build setup is improperly configured. If you are using Cocoapods, maybe you should try running `pod install` again and make sure you are opening the workspace created by Cocoapods and not just your project. If you are building manually, make sure that the AlgoliaSearch module is added as a dependency and compiled for all software architectures.

**Comment by proactive-solutions** [comment]
I used Carthage to build framework and everything was ok. Thanks for the prompt reply :)
