### ISSUE TITLE
Provide a synchronous flavour of query methods

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-swift#31]
That's something we do in other clients. It can be useful when the user already has a background thread which she uses to perform operations. In this case, synchronous calls lead to more straightforward code while not degrading end-user performance.

**Comment by clement-leprovost-algolia** [comment]
Not convinced that this is still required, because we now return an `NSOperation` from all asynchronous operations. Therefore the user can call `NSOperation.waitUntilFinished()` if necessary.
-> Removing from the v3 roadmap.

**Comment by spinach** [comment]
Can we close this @clement-leprovost ?

**Comment by robertmogos** [comment]
I don't see the value with the existing implementation. Let's close it
