### ISSUE TITLE
Discard the custom type alias `JSONObject`?

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-swift#335]
This type alias had two goals:

1. Serve as a documentation.
2. Act as a shield against constant changes in the Swift API between Swift 2 and Swift 3.

Point number 2 obviously doesn't hold any longer. It turns out that point number 1 is not obvious either. A custom type alias conveys clear semantics, so that's good. But it may also be counterproductive. When I encounter a custom type in a third-party library, I tend to think "oh, it's a class that I have to instantiate".

So I guess it's mostly a matter of style... but style matters too! :) => Happy to hear anyone's feedback on this one.

**Comment by spinach** [comment]
I fully agree with you. When I first tried the library, I remember seeing this `JSONObject` type and thought that I had to do some extra steps in order to use the function that had it as param. I think that it would be better to keep the [String:Any] as the type. 

So I vote to discard the custom type alias 👍

**Comment by spinach** [comment]
@robertmogos Would like your opinion on that as well so that we can move forward 🙂

**Comment by robertmogos** [comment]
Indeed, I don't see a lot of value in having `JSONObject`. My only concern is that if we remove it, we would break our customers code. So maybe we move from `JSONObject` to `[String:Any]` on our side and just deprecate `JSONObject`

**Comment by spinach** [comment]
Agreed for the deprecation 👍 Let's do that

**Comment by robertmogos** [comment]
Closing it since was deprecated in 5.0
