### ISSUE TITLE
xcode 8.3 error: Reference to generic type Index requires arguments in <...>

### ISSUE THREAD

**Issue by kiwo12345** [algolia/algoliasearch-client-swift#368]
I just updated to xcode 8.3 and now I get the error: Reference to generic type Index requires arguments in <...>

from this line:
`var myIndex: Index!`

Any idea how to fix it?

**Comment by clement-leprovost** [comment]
The `Index` class in the the Swift Client is not generic, so this error is most probably not linked to the Algolia library.

Would you happen to be using another library defining an `Index` class as well? Maybe SwiftyJSON? Could it be something similar to the [SwiftyJSON - var searchIndex: Index! Error](https://discourse.algolia.com/t/swiftyjson-var-searchindex-index-error/759) post on Algolia Community?

**Comment by kiwo12345** [comment]
@clement-leprovost Oh yeah right!
`var myIndex: AlgoliaSearch.Index!` Fixed it :)
