### ISSUE TITLE
Query advancedSyntax bool?

### ISSUE THREAD

**Issue by MattTimmons** [algolia/algoliasearch-client-swift#37]
I found typoTolerance as an enum in Query.. but can not find advancedSyntax? Any ideas?

**Comment by redox** [comment]
Indeed, this query parameter seems to be missing. We'll add it shortly!

**Comment by clement-leprovost-algolia** [comment]
Already implemented in the v3 branch.

**Comment by MattTimmons** [comment]
great. when is the expected "v3" release?

**Comment by clement-leprovost-algolia** [comment]
No ETA yet for the v3, sorry.

**Comment by MattTimmons** [comment]
ah, what are the chances to merge that feature earlier then?

**Comment by clement-leprovost-algolia** [comment]
The changes are unmergeable because the `Query` class has been completely refactored in the v3. So depending on how urgent it is, what we could do is re-implement it in the v2.

**Comment by MattTimmons** [comment]
thats fine. if it is more than a 1.5month+ wait, I would prefer an earlier merge, otherwise I can wait.

**Comment by clement-leprovost-algolia** [comment]
Version 3.0 released.
