### ISSUE TITLE
Xcode 7.3: lot of warnings

### ISSUE THREAD

**Issue by TofPlay** [algolia/algoliasearch-client-swift#38]
Hi,
After installed Xcode 7.3 when I build with Carthage I have a lot of warnings:
```
warning: 'var' parameters are deprecated and will be removed in Swift 3
warning: '++' is deprecated: it will be removed in Swift 3
warning: keyword 'protocol' does not need to be escaped in argument list
warning: use of 'typealias' to declare associated types is deprecated; use 'associatedtype' instead
```

**Comment by dethi** [comment]
Already fixed by #36, just need to be release!

**Comment by clement-leprovost-algolia** [comment]
Yes, that's the plan! I just thought there was no real hurry: Swift 2.2 has only been out for less than a week, so I guess Swift 3 will not be out tomorrow. :)

**Comment by argon** [comment]
These warnings make our CI output unreadable as it generates output for every single Swift file in our project (we can't use frameworks unfortunately) so the sooner this can be released the better, for us :pray:

**Comment by clement-leprovost-algolia** [comment]
FYI: #36 merged, also solves this one.
