### ISSUE TITLE
Support Swift 4

### ISSUE THREAD

**Issue by spinach** [algolia/algoliasearch-client-swift#388]
Although Apple officially supports mixed dependencies with Swift 3.2 and 4, devs using CocoaPods might run into problems today, as there's no way to set the Swift version on a per-pod basis.

When trying to compile the library in Swift 4, we get one error in the `shuffleInPlace` function inside the `MutableCollection` extension.

> Simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable. Replace 'swap(&self[i], &self[j])' with 'self.swapAt(i, j)'

I propose to submit a PR to address this issue asap and release a version 5-beta1 of the library since it targets a new Swift Version. Later on,  I will include a few PRs for resolving issues such as #335 and #259 and then I will release v5. 

WDYT?

**Comment by clement-leprovost** [comment]
Doesn't the `.swift-version` trick work any longer?

**Comment by spinach** [comment]
@clement-leprovost Does not work, I tested it.
Check [this issue](https://github.com/CocoaPods/CocoaPods/issues/6791) in CocoaPods for more info.

**Comment by clement-leprovost** [comment]
@spinach IMHO, releasing a new major version should involve more than just fixing one line of code! All the breaking changes we identified in the `v5` milestone should be addressed before releasing a beta. (In theory, a beta version should be feature complete and not evolve feature-wise.)

Since Swift 4 is not supposed to be officially released before Fall, I guess we have some time left... 🙂

I would advise to start two branches:

- A `swift-4` branch for Swift 4 compatibility. Those who want to use the API Client with Swift 4 can always target this branch (using the `:branch` option) from their `Podfile`.
- A `v5` branch for the upcoming major version.

Of course at some points these two branches will have to be merged, but at least we are keeping them separate, thus leaving the possibility to clients to use Swift 4 without having to deal with the backward incompatibilities incurred by the new major version.

**Comment by spinach** [comment]
@clement-leprovost All good points, I like the two branches approach. Let's go for that 💯

**Comment by ismyhc** [comment]
I just took a look and didn't see a swift-4 branch. Is there an estimate on when there will be a swift 4 compatible version?

**Comment by spinach** [comment]
Hi @ismyhc, 
We'll make sure to have this branch ready before the release of Xcode 9. I will work on it at the end of this week (and next week if not done), stay tuned!

**Comment by ismyhc** [comment]
@spinach Awesome! Thanks!

**Comment by spinach** [comment]
@ismyhc You can follow the updates ^

**Comment by spinach** [comment]
For now: Swift 4 is available using cocoaPods by adding the following to your Podfile:
```
pod 'AlgoliaSearch-Client-Swift', :git => "https://github.com/algolia/algoliasearch-client-swift.git", :branch => "swift-4”
```

**Comment by ismyhc** [comment]
@spinach Thanks so much! We got a head start this week on a new project by installed the latest beta Xcode knowing the gm should be out pretty soon. :)

**Comment by spinach** [comment]
Didn't manage to make it work for Carthage quite yet. 

I am adding the following in `Cartfile`:
```
github "algolia/algoliasearch-client-swift" "swift-4"
```

For some reason I am getting:
```
The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET AlgoliaSearch iOS OF PROJECT AlgoliaSearch WITH CONFIGURATION Release ===

Check dependencies
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: no umbrella header found for target 'AlgoliaSearch iOS', module map will not be generated

** BUILD FAILED **
```
Although in the project, I clearly specified the SWIFT_VERSION to be Swift 4. Will investigate further..

**Comment by spinach** [comment]
Carthage works as well, what needed to be done is to point xcode to the new beta version by doing so:

`xcode-select -switch <path>`

Example:

`xcode-select -switch /Applications/Xcode-beta.app`

And don't forget to specify in your Cartfile:

`github "algolia/algoliasearch-client-swift" "swift-4"`

**Comment by spinach** [comment]
You can now use Version 5+ which has been released for Swift 4.
