### ISSUE TITLE
Remove admin API key-only operations

### ISSUE THREAD

**Issue by clement-leprovost-algolia** [algolia/algoliasearch-client-swift#44]
It does not make sense to have client methods for requests requiring an admin API key, as this key should remain on the back-end.

So we should remove:
- Global API keys management
- Per-index API keys management
- Logs retrieval

**Comment by dethi** [comment]
Can be useful for people who will use swift as a backend language in one or two years ;-)
#swift3

**Comment by clement-leprovost-algolia** [comment]
Well, I'm always been a fan of science-fiction, but it's already complicated to plan for the present, so let's not venture too far into the future... :smile:

**Comment by clement-leprovost-algolia** [comment]
Implemented in the `v3` branch, waiting for release.
