### ISSUE TITLE
Swift Compiler Error in Helpers.swift: Value of type 'Self' has no member 'swapAt'

### ISSUE THREAD

**Issue by andreyguenov** [algolia/algoliasearch-client-swift#495]
Hello, 

I just installed the Swift Algolia Search client by following the instructions here: https://github.com/algolia/algoliasearch-client-swift

I have included the ```pod 'AlgoliaSearch-Client-Swift'``` line in the Podfile and ran ```pod install``` (and ```pod update``` just to be sure). 

When compiling the project I am getting the following error: Swift Compiler Error in Helpers.swift: Value of type 'Self' has no member 'swapAt'. 

![snip20171203_1](https://user-images.githubusercontent.com/6558274/33520285-80684d7a-d7c0-11e7-9146-c4bd67e56429.png)
![snip20171203_2](https://user-images.githubusercontent.com/6558274/33520286-808408e4-d7c0-11e7-9dab-09c735a99e82.png)

I don't think it might be relevant to this particular issue, but I am also having issues with getting XCode to recognize the ```import AlgoliaSearch``` statement. I am still struggling with a 'No such module'. I though I might mention it just in case they are connected.

I am using Swift 3 on XCode Version 8.2.1 (8C1002). 

Thank you!

**Comment by spinach** [comment]
Hey @andreyguenov ,

So the reason for this is that you're fetching the swift 4 version of the library which is not compatible with the Swift 3 version that you're using. Two possible solutions:

- You can use use the [swift-3](https://github.com/algolia/algoliasearch-client-swift/tree/swift-3) branch and you can use with cocoapods like [this](https://stackoverflow.com/a/39930762/905425). This is equivalent to using version 4.8.1: `pod 'AlgoliaSearch-Client-Swift', '~> 4.8.1'`
- You can use Xcode 9 and Swift 4, run `pod update` and things should run smoothly.

**Comment by andreyguenov** [comment]
Hey, @spinach! Thanks for the quick reply on a Monday!

Could I suggest you include a small note of this in your README file? I think there are still some Swift 3 users out there who will benefit from this. 

Thanks again and have a great day!

**Comment by spinach** [comment]
@andreyguenov Definitely agree, thanks for feedback! I'll do that right away 🙂
