### ISSUE TITLE
`client.searchTimeout, client.timeout` not work

### ISSUE THREAD

**Issue by WANGjieJacques** [algolia/algoliasearch-client-swift#543]
I set 
```
client.timeout = 3
client.searchTimeout = 3
```

but, it timeouts in like 30 seconds.

**Comment by spinach** [comment]
Hi @WANGjieJacques,

Let me tell you what's going on in the `client` concerning the `timeout`: 

- The client has a retry strategy on different hosts in case one of them fails. Take a look at `init(client: AbstractClient, method: HTTPMethod, hosts: [String], ...`. By default we retry on 3 different hosts if you don't specify anything.
- Every time we retry, we increase the timeout for the next request by doing `self.nextTimeout += self.timeout`. So in your case, if you set the timeout to be 3, it will actually be in total 3+6+9 = 18 seconds which feels much longer than 3. But effectively, the first request will have a timeout of 3 seconds.

**Comment by WANGjieJacques** [comment]
@spinach thanks.
