### ISSUE TITLE
CocoaPods warning regarding HTTP

### ISSUE THREAD

**Issue by matheda** [algolia/algoliasearch-client-swift#556]
CocoaPods 1.4.0 issues the following warning when doing a 'pod install':

[!] 'AlgoliaSearchOfflineCore-iOS' uses the unencrypted http protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts in there. Please reach out to the library author to notify them of this security issue.

**Comment by Aadesh5** [comment]
I am also recieving the same issue when I try to update 'AgoraRtcEngine_iOS' pod

**Comment by spinach** [comment]
Hello,

Sorry for the lack of response on that. This is an issue that arises when using the offline version of our library. 

We are aware of it and will work on fixing it. Unfortunately, it is not a straightforward change, as the offline SDK needs to be rebuilt and tested with all the new changes of our engine. The online SDK does not have this problem though. 

We'll update you when this gets fixed. Thank you for reporting that!

**Comment by spinach** [comment]
Offline tests passed locally

**Comment by spinach** [comment]
This should be solved on Cocoapods version 6.1.0
