### ISSUE TITLE
Support all search parameters

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-swift#557]
Some [documented search parameters](https://www.algolia.com/doc/api-reference/api-parameters/) are not supported, like `optionalFilters`. Could we consider adding support?

**Comment by PLNech** [comment]
Reviewing both android and swift clients surfaced these missing `search` parameters:

`optionalFilters`
`sumOrFiltersScores`
`clickAnalytics`

I'll implement the two former in the Android client; I believe the latter should be released along with the implementation of Insights API.

**Comment by jobernas** [comment]
Any progress on this for Swift?

**Comment by robertmogos** [comment]
Hi @jobernas. We are going to work on this in the next two weeks. I'll get back to you when we are releasing this

**Comment by robertmogos** [comment]
Fixed in 5.3.0
