### ISSUE TITLE
Support array of strings for value of urlParameters["optionalFilters"]

### ISSUE THREAD

**Issue by adrienjoly** [algolia/algoliasearch-client-swift#560]
As reported by Matt T., from https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/ :

> Swift syntax for optional filters is incorrect on this document 
> 
> let requestOptions = RequestOptions() 
> requestOptions.urlParameters["optionalFilters"] = ["category:Book", "author:John Doe"] 
> 
> Complier want string, not [String]. 
> Could you please provide proper syntax? 
> Cheers, 
> - Matt

Could be related to #557.

**Comment by robertmogos** [comment]
Fixed here: https://github.com/algolia/algoliasearch-client-swift/commit/b5f99b5aed08f37561d389b713a30d4f7159c552
