### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by dsdsk** [algolia/algoliasearch-client-swift#563]
Nice to meet you.
I'm trying to use InstantSearchClient, but I get a build error.
Please tell me the solution.

I installed InstantSearchClient with cocoapods.
```
pod 'InstantSearchClient', '~> 5.0'
```

After that, when I opened the project, a build error appeared after the following dialog was displayed.
<img width="419" alt="2018-06-10 18 21 42" src="https://user-images.githubusercontent.com/33220890/41200221-6a18b252-6cdb-11e8-961a-289527022498.png">
```
The "Swift Language Version" (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

Looking at the build setting of InstantSearchClient, the Swift Language Version is Unspecified.
<img width="556" alt="2018-06-10 18 21 54" src="https://user-images.githubusercontent.com/33220890/41200234-ad70e61e-6cdb-11e8-98d6-6f8a0fcd488e.png">

The environment is
Xcode 9.4
Cocoapods 1.5.3

It is developing with Objective-C.

Podfile
```
platform :ios, '9.0'
use_frameworks!
swift_version= '4.1'

target 'TestProject' do
	pod 'InstantSearchClient', '~>5.0'
end
```

I write sentences using Google Translate.
I am sorry if the sentences are wrong.

**Comment by spinach** [comment]
Hey @dsdsk 

Can you add the following to your Podfile to tell it to build for Swift 4?

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end
```

If you want the above to only apply to InstantSearchClient library, then follow the steps [here](https://stackoverflow.com/a/46690240/905425).

**Comment by dsdsk** [comment]
It went well. Thank you.
