### ISSUE TITLE
I got the error Cannot invoke 'Client' with an argument list of type '(appID: String, apiKey: String)'

### ISSUE THREAD

**Issue by lioneltan** [algolia/algoliasearch-client-swift#567]
let client = Client(appID: "FL0M3YR7T6", apiKey: "ea1f01915288449ab0c65b9999f5f2ea")
        let index = client.index(withName: "your_index_name")

I got the error Cannot invoke 'Client' with an argument list of type '(appID: String, apiKey: String)'

These are the pods:
pod 'AlgoliaSearch-Client-Swift'
pod 'InstantSearchClient', '~> 5.0'

**Comment by lioneltan** [comment]
Hi, the code in the documentation are not working..I even tried node.js based on documentary also not working.

**Comment by lioneltan** [comment]
Firstly, the // Load content file
let jsonURL = Bundle.main.url(forResource: "contacts", withExtension: "json")
let jsonData = try! Data(contentsOf: jsonURL!)
let dict = try! JSONSerialization.jsonObject(with: jsonData!)

// Load all objects in the JSON file into an index named "contacts".
let index = client.index(withName: "contacts")
index.addObjects(dict["objects"])

is not working.

**Comment by spinach** [comment]
@lioneltan Did you make sure to add the `contacts.json` file in your project?
If yes, then what error are you getting in your error stack? can you paste it here?

**Comment by lioneltan** [comment]
Yes added..at this line index.addObjects(dict["objects"]) i got this error:
Type 'Any' has no subscript members

**Comment by spinach** [comment]
`addObjects` expects a `[[String: Any]]`as its argument. Did you try to cast `dict["objects"]` to `[[String: Any]]`?
