### ISSUE TITLE
RunLoop has no member Mode

### ISSUE THREAD

**Issue by tbarbugli** [algolia/algoliasearch-client-swift#573]
I get this on a new project after installing the InstantSearchClient 6.0.0 pod.

```
/.../SearchProject/Pods/InstantSearchClient/Sources/AlgoliaSearch-Client/Cache.swift:56:41: Type 'RunLoop' has no member 'Mode'
```

I am using XCode 9.4.1 on High Sierra

**Comment by spinach** [comment]
Hi @tbarbugli ,

You should use Version `5.0` which is for `Swift 4.1` since it seems you're still using XCode 9. It is currently documented [here](https://github.com/algolia/algoliasearch-client-swift#swift-41).
