### ISSUE TITLE
New release on Cocoapods

### ISSUE THREAD

**Issue by pmusolino** [algolia/algoliasearch-client-swift#575]
Hi.
When do you have in plan to release the latest version of AlgoliaSearch-Client-Swift on Cocoapods? I see that the last release is the v.5.1.7, that is not compatible with Swift 4.2.

-Paolo

**Comment by spinach** [comment]
Hi @pmusolino - you can use `pod InstantSearchClient` version 6 that is compatible with Swift 4.2. Checkout the instructions in the README [here](https://github.com/algolia/algoliasearch-client-swift#swift-42).
