### ISSUE TITLE
Issue when importing with SPM in Xcode 11

### ISSUE THREAD

**Issue by mackoj** [algolia/algoliasearch-client-swift#612]
**Describe the bug 🐛**

When adding this repo with Xcode 11 as a SPM dependency it's does not compile

**To Reproduce 🔍**

Create a new project of Xcode then go to File -> Swift Package Manager -> Add Dependency -> paste the URL of the git repo

**Expected behavior 💭**

The app should compile.

**Screenshots 🖥**

This is one of the issue

![Capture d’écran 2019-06-07 à 16 51 20](https://user-images.githubusercontent.com/661647/59112996-82fe5c00-8944-11e9-932c-6e2398a73327.png)

I think you should set a swift version in your Package.swift file too.

**Environment:**
 - OS: OSX Catalina

**Comment by quanvo87** [comment]
This would get fixed by https://github.com/algolia/algoliasearch-client-swift/pull/614 if it gets merged.

**Comment by spinach** [comment]
Fixed in #616
