### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by leontedev** [algolia/algoliasearch-client-swift#615]
**Describe the bug 🐛**
I've recently installed Xcode 11 GM - and I tried building my project however I receive the following error on import InstantSearchClient

Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Documents/Dev/Timely2/Carthage/Build/iOS/InstantSearchClient.framework/Modules/InstantSearchClient.swiftmodule/x86_64.swiftmodule

**To Reproduce 🔍**
1. Cartfile: github "algolia/algoliasearch-client-swift" ~> 7.0.0
2. Xcode 11 GM
3. Build project
4. See error:

Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Documents/Dev/Timely2/Carthage/Build/iOS/InstantSearchClient.framework/Modules/InstantSearchClient.swiftmodule/x86_64.swiftmodule

**Environment:**
 - OS: Mac OS Catalina beta 8 
 - Xcode 11 GM

**Comment by quanvo87** [comment]
https://stackoverflow.com/questions/41442601/whats-the-purpose-of-no-use-binaries-in-carthage

> Executing the update command might occasionally produce an error when the Swift language updates to a newer version while the dependency is built for an older version of Swift (even if it’s still compatible)

You can remedy this with `carthage update algoliasearch-client-swift --platform iOS --no-use-binaries`.

Make sure your Command Line Tools is pointed to Xcode 10.3. To do this, go to Xcode, then `⌘ + ,` > Locations > Command Line Tools > choose Xcode 10.3.

**Comment by leontedev** [comment]
Thanks @quanvo87. I wasn't aware of that flag.
