### ISSUE TITLE
Filter.Numeric not working with large integer (i.e. timestamps)

### ISSUE THREAD

**Issue by aplusm** [algolia/algoliasearch-client-swift#623]
INFO: The same bug report has been added to the instantsearch-ios repository (https://github.com/algolia/instantsearch-ios/issues/97)

Describe the bug 🐛
I have a date_timestamp in my index, and would like to add a Filter.Numeric to my FilterState.
The filter is not respected and no results is returned.

To Reproduce 🔍

let nowTimestamp = Float(NSDate().timeIntervalSince1970)
let filter = Filter.Numeric(attribute: "date_timestamp", operator: .greaterThanOrEqual, value: nowTimestamp)
filterState[and: "calendar"].add(filter)
...
This doesn't returns any results as it should be, based on my index data.

Expected behavior 💭
The filter should returns the correct answer.

Environment:

OS: iOS
Version 5.2.2

**Comment by spinach** [comment]
I guess this is solved, is that correct @VladislavFitz ? can we close it?

**Comment by VladislavFitz** [comment]
@spinach Yes, it's solved in the patch `6.5.3` of [InstantSearch Core](https://github.com/algolia/instantsearch-core-swift)
