### ISSUE TITLE
Dependency on AFNetworking will cause Apple Review rejections after April 2020

### ISSUE THREAD

**Issue by aliofye** [algolia/algoliasearch-client-swift#624]
**Describe the bug 🐛**
Due to the dependency on AFNetworking which is refusing to update their pod to remove any mention of the deprecated UIWebView APIs, Apple Review will start rejecting any app that uses AlgoliaSearch-Client 3.5 (AFNetworking ~> 2.2)

**Expected behavior 💭**
Remove any dependency on AFNetworking, right now, if I want to use AlgoliaSearch-Client v3.5 I have to install it's dependencies and that will cause rejections by Apple

**Proposed Solution**
in the Podfile change it to the following:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.9'
workspace 'algoliasearch-client-objc'
pod 'AFNetworking/Reachability', '~> 2.4.0'
pod 'AFNetworking/Serialization',  '~> 2.4.0'
pod 'AFNetworking/Security',  '~> 2.4.0'
pod 'AFNetworking/NSURLSession',  '~> 2.4.0'
pod 'AFNetworking/NSURLConnection', '~> 2.4.0'
```
Which will remove the problamatic module
```pod 'AFNetworking/UIKit', '~> 2.4.0'```

**Comment by spinach** [comment]
Hello,

Thank you for contacting us. and sorry for the late reply. 

It seems you are referring to our deprecated [Objc API Client](https://github.com/algolia/algoliasearch-client-objc). As noted in the README: 

> In July 2015, we released our Swift API Client, able to work with Swift and Objective-C. As of version 3 (April 2016), Swift has become the reference implementation for both Swift and Objective-C projects.

> This Objective-C API Client is no longer under active development. It is still supported for bug fixes, but will not receive new features.

The objc client has been deprecated for more than 4 years. 
Removing AFNetworking is unfortunately not a bug fix, as AFNetworking is used everywhere in the [client](https://github.com/algolia/algoliasearch-client-objc/blob/4b424f2b331c62d15b94487d234bc1909adf7be0/src/ASAPIClient.h). Therefore, we advise that you update to our new Swift API Client (it does have support for Obj-C).
