### ISSUE TITLE
Unexpected version number in 'available' attribute for non-specific platform '*'

### ISSUE THREAD

**Issue by OmegaWulf** [algolia/algoliasearch-client-swift#628]
**Describe the bug 🐛**
7 Warnings in Xcode: 
Unexpected version number in 'available' attribute for non-specific platform '*'

**To Reproduce 🔍**
1. Use Xcode 11.4 with a Swift 5 project
2. Install v7.0.3
3. Build
4. Check warnings 

**Expected behavior 💭**
No warnings

**Screenshots 🖥**
<img width="1520" alt="Screen Shot 2020-03-27 at 10 23 35 PM" src="https://user-images.githubusercontent.com/42750678/77815603-9d432b00-7079-11ea-8c1c-0fe52e58c4aa.png">

**Environment:**
MacOS 10.15.4
Xcode 11.4

**Comment by spinach** [comment]
Hi @OmegaWulf ,

Thank you for reporting this. We should indeed solve new warnings that come up with new Xcode versions.

In the meantime on your end, if you don't want to see the warnings with cocoapods, you can take a look at this [SO thread](https://stackoverflow.com/a/13209057/905425) to remove the clutter.

Thanks again!

**Comment by VladislavFitz** [comment]
Not relevant since the release of the new major of the Client
