### ISSUE TITLE
filterState[or: "group"].removeAll() not working

### ISSUE THREAD

**Issue by aplusm** [algolia/algoliasearch-client-swift#629]
Xcode 11.4.1
InstantSearchClient 7.0.3
InstantSearchCore 6.6.3

Calling removeAll() on a disjunctive group returns an error:

`Generic parameter 'F' could not be inferred`

Calling removeAll() on a conjunctive group is OK, as well as adding a filter to a conjunctive/disjunctive group.

**Comment by aplusm** [comment]
A related error (i think):

`filterState[or: "category"].addAll(bannerFilters())` 
where `bannerFilters()` return an array of `FilterType`

triggers the following error: 

**Value of protocol type 'FilterType' cannot conform to 'FilterType'; only struct/enum/class types can conform to protocols**

**Comment by VladislavFitz** [comment]
Hey @aplusm. Thank you for reaching out.

Unlike the conjunctive group, the disjunctive one [may only contain the filters of the same type](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/combining-boolean-operators/#caveats). That means that you have to explicitly precise the filter type of disjunctive group each time it cannot be inferred. So the errors you faced are intended as they prevents the ambiguity at compile time.  

For example, `filterState[or: "category", Filter.Facet.self]` and `filterState[or: "category", Filter.Tag.self]` are considered as **two different groups** of filters and are stored separately under the hood. 

Thus the `filterState[or: "group"].removeAll()` call is ambiguous, as the filter type is not set explicitly, while
`filterState[or: "filterFacets", Filter.Facet.self].removeAll()` or `filterState[or: "filterFacets", Filter.Tag.self].removeAll()` are working well.

This is also true in the case of adding multiple filters: when you call `filterState[or: "category"].addAll(bannerFilters())`, the type of the filter is undefined. You have to convert your list of filters to a concrete filter type, for example:

```
let facetFilters = bannerFilters().compactMap { $0 as? Filter.Facet }
filterState[or: "category"].addAll(facetFilters)
```

I hope this answers your question.
