### ISSUE TITLE
Partial Update Object, Multiple Attributes

### ISSUE THREAD

**Issue by rayfarer** [algolia/algoliasearch-client-swift#651]
**Describe the bug 🐛**
I'm confused regarding how Partial Update Object works now in the Swift Algolia client.

I want to partially update an object and change multiple (not all) attributes without having to use Save Object. I could do this easily in the previous version by providing my own JSON object.

The documentation does not provide an example of changing multiple attributes for a single object, but it says it can. All I see is this:

`index.partialUpdateObject(withID: "myID", with: .update(attribute: "city", value: "San Francisco")) { result in
  if case .success(let response) = result {
    print("Response: \(response)")
  }`

That's great if I only want to update city. But what if I wanted to update city and some other attribute? Say I have an object for a customer named Bob. I've changed his city, but how do I change his age _and_ city? I feel like I'm missing something obvious, but would appreciate a point in the right direction.

Thanks!

**Environment:**
iOS

**Comment by VladislavFitz** [comment]
Hi @rayfarer,
As I answered on Discourse, we consider to put back this feature in the next release.
In the meantime, please use `index.partialUpdateObjects` batching method.

**Comment by rayfarer** [comment]
Thanks again for addressing this issue very promptly earlier this year, but could you perhaps offer some guidance on how to use this properly (and perhaps update [this page](https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/) with an example? 

In the past, I was able to use a dictionary to partially update an object, but I am unfamiliar with this "PartialUpdate" type. I want to do something like this:

```
let updatedAlgoliaObject  = [
            "collection" : collection,
            "quantity" : quantity,
    ] as [String : Any]

index.partialUpdateObject(withID: "userAccountID", with: updatedAlgoliaObject)
```

In this case, collection is a String quantity is an Int. Getting the error message "Cannot convert value of type '[String : Any]' to expected argument type 'PartialUpdate'"

What I'm really asking is, how do I provide my own values to build a dictionary that will be accepted by partialUpdateObject?
