### ISSUE TITLE
Overriding a public method in the HitsTableViewController

### ISSUE THREAD

**Issue by georgepliuster** [algolia/algoliasearch-client-swift#653]
**Describe the bug 🐛**
I have an existing ViewController that uses TableViewDelegate, UITableViewDataSource with an array collection as a data source - a classical setup.  I want to add a search bar and the inherit the HitTableViewController, allowing me to present my data either via the array collection or using the search bar.  Depending on the mode of search (array or instant search) I will populate the table accordingly.  Unfortunately the data source methods within the HitsTableViewController are declared public.  Therefore I cannot override them in my inherited view controller.  I tried extending my ViewController, but that does not work.

Aside from changing the data source method to open from public in the HitsTableViewController, do I have any other options?

Thanks

**To Reproduce 🔍**

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**
 - OS: [e.g. iOS / windows / mac / android]

**Additional context**

**Comment by VladislavFitz** [comment]
Hello @georgepliuster 

Sorry for delayed response. 
The usage of `HitsTableViewController` is not mandatory, you can just add a conformance to `HitsController` protocol to your own `ViewController` and then connect it to your `HitsInteractor`. 
**Pro tip**: if your `ViewController` presents the hits in the instance of `UITableView`, add conformance to `HitsTableViewContainer` protocol to your view controller, returning your table view via `hitsTableView` property: 
```swift
var hitsTableView: UITableView {
  return myTableView
}
```
By doing this, you get the implementations of `reload` and `scrollToTop` methods of  `HitsController` protocol for free.

**Comment by georgepliuster** [comment]
Hello Vladislav,

Good to hear from you.  No worries about the delayed response.

Adding a conformance to the HitsController protocol is a great idea and I
will give it a try.

Thanks!

**Comment by VladislavFitz** [comment]
You are welcome!
