### ISSUE TITLE
Change PlacesQuery.language property to public

### ISSUE THREAD

**Issue by jeremierichard** [algolia/algoliasearch-client-swift#655]
Hello,

I need to set the `language` property of a `PlacesQuery` as described in the [swift documentation](https://community.algolia.com/places/api-clients.html#swift-api-client) but the scope of the property is `internal`

Do you plan to expose it public soon ?

I am using the Release `8.1.0` of `AlgoliaSearchClient`

https://github.com/algolia/algoliasearch-client-swift/blob/c47d9a62fb02a876305dd739e6457c2b054ae7e2/Sources/AlgoliaSearchClient/Models/Places/PlacesQuery.swift#L41

**Comment by jeremierichard** [comment]
Using `InstantSearchClient` instead of `AlgoliaSearchClient` gives access to the property.
By the way, I am a bit confused about those two SDKs. Which one is recommended ?

**Comment by VladislavFitz** [comment]
Hi @jeremierichard,

`AlgoliaSearchClient` is the new name of `InstantSearchClient`, so we recommend to use the `AlgoliaSearchClient` as it's the latest version of the Swift Client.
 
The property `language` is set `internal` intentionally.
`PlacesClient` provides two `search` methods:
 
```swift
func search(query: PlacesQuery, requestOptions: RequestOptions? = nil, completion: @escaping ResultCallback<MultiLanguageResponse>) -> Operation
```
and

```swift
func search(query: PlacesQuery, language: Language, requestOptions: RequestOptions? = nil, completion: @escaping ResultCallback<SingleLanguageResponse>) -> Operation
```

Using the second one you can specify the language and get `PlacesClient.SingleLanguageResponse` in the callback, while the callback of the first method returns `PlacesClient.MultiLanguageResponse` containing the values in all available languages. This approach makes possible to ensure the correct response value in compile time.

Thank you for feedback. This remark will be added to the code documentation to make it clear.

**Comment by jeremierichard** [comment]
Thank you, that's clear.
