### ISSUE TITLE
Crash: "Fatal error: Can't form Range with upperBound < lowerBound"

### ISSUE THREAD

**Issue by jinfu-leng** [algolia/algoliasearch-client-swift#659]
**Describe the bug 🐛**
When searching for certain keywords, the client crashes.

**Screenshots 🖥**
Stack trace
![Screen Shot 2020-09-03 at 8 43 31 AM](https://user-images.githubusercontent.com/1676593/92137537-16317600-edc2-11ea-85ce-63b38027a9a3.png)

**Environment:**
 - OS Version: 13.2
 - Package Version: 8.1.0

**Comment by VladislavFitz** [comment]
Hi @jinfu-leng 
Thanks a lot for your feedback. 
Could you give an example(s) of the keyword causing the crash?

**Comment by jinfu-leng** [comment]
> Hi @jinfu-leng
> Thanks a lot for your feedback.
> Could you give an example(s) of the keyword causing the crash?

It crashed when searching for "goog" (I was in the process of typing "google"). Thinking about this again, the crash might be related to the indexed content as well.

(If you need additional data to reproduce the bug, please PM me and you can test on our index.)

**Comment by VladislavFitz** [comment]
It's most likely related to the indexed content, so it would be helpful if you sent me a json response with search results you received before the crash.

Feel free to send me an email to vladislav.fitc@algolia.com.

**Comment by VladislavFitz** [comment]
After investigation, a [new issue](https://github.com/algolia/algoliasearch-client-swift/issues/662) created.
