### ISSUE TITLE
SearchResponse's automaticRadius is wrong type

### ISSUE THREAD

**Issue by TateB** [algolia/algoliasearch-client-swift#669]
**Describe the bug 🐛**
Within the SearchResponse struct, the automaticRadius is set to a double, while the JSON response actually has it set to a string. Could be very easily fixed switching the double back to a string.

**To Reproduce 🔍**
1. Send a query with aroundLatLng or aroundLatLngViaIP enabled
2. Parse query response through SearchResponse struct
3. An error will occur, trying to convert automaticRadius String to the expected Double

**Expected behavior 💭**
The SearchResponse parses correctly without error.

**Environment:**
 - OS: iOS
 - Version 14.0

**Comment by VladislavFitz** [comment]
Hi @TateB ,

Thanks a lot for pointing this. 
A fix will arrive soon 🔧
