### ISSUE TITLE
Project fails to build when adding 8.1.1 through SPM

### ISSUE THREAD

**Issue by quanvo87** [algolia/algoliasearch-client-swift#670]
**Describe the bug 🐛**
I get this error when adding 8.1.1 through SPM:
`The package product 'Logging' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0`

I also get this warning:
`The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

**To Reproduce 🔍**
Create a new project. Add algolia 8.1.1 through SPM.

**Expected behavior 💭**
Builds successfully.

**Environment:**
Xcode 12

**Comment by VladislavFitz** [comment]
Hi @quanvo87,
Thank you for your feedback. 
The fix for this issue will be released soon!
