### ISSUE TITLE
Pod 3.2 not compatible with OS X?

### ISSUE THREAD

**Issue by MattTimmons** [algolia/algoliasearch-client-swift#68]
(OS X 10.11) is not compatible with `AlgoliaSearch-Client-Swift (3.2)`, which does not support `osx`.

**Comment by clement-leprovost** [comment]
@MattTimmons Probably a side effect of the introduction of subspecs. The Online subspec, which is normally the default, *does* support OS X (but not the Offline one so far). So in theory it should work... but obviously doesn't. :D

You can try as a temporary workaround:

1. explicitly depend on the Online subspec: `pod 'AlgoliaSearch-Client-Swift/Online'`; or
2. pin the 3.1 version: `pod 'AlgoliaSearch-Client-Swift', '~> 3.1'`

... until I fix the issue. Sorry for the inconvenience.

**Comment by clement-leprovost** [comment]
Fixed by version 3.2.1.
