### ISSUE TITLE
InstantSearchClient migration - Replacement for `searchDisjunctiveFaceting` ?

### ISSUE THREAD

**Issue by jeremierichard** [algolia/algoliasearch-client-swift#684]
Hello 🙂 

I am migrating from `InstantSearchClient` to `AlgoliaSearchClient` and I am not able to find a replacement for `searchDisjunctiveFaceting` method.
My Android colleague use the Kotlin method [advancedSearch line 95](https://github.com/algolia/algoliasearch-client-kotlin/blob/9ca03914bf6f1a14bbb64823498b61a909fb5c9d/src/commonMain/kotlin/com/algolia/search/endpoint/internal/EndpointSearch.kt), but I don't have the equivalent of `advancedSearch` on the iOS version.

Do you plan to integrate the `searchDisjunctiveFaceting` or `advancedSearch` method in the iOS SDK ? 

If not, how am I supposed to use a `searchDisjunctiveFaceting` like request ?

Thanks

**Comment by VladislavFitz** [comment]
Hello @jeremierichard,

For iOS disjunctive faceting is available as a part of our [InstantSearch](https://github.com/algolia/instantsearch-ios) library. 
You have to use [SingleIndexSearcher](https://www.algolia.com/doc/api-reference/widgets/instantsearch/ios/#singleindexsearcher) with a connected [FilterState](https://www.algolia.com/doc/api-reference/widgets/filter-state/ios/). 

The `SearchResponse` you get via  `onResults` observer will contain the correct facets information.

**Comment by jeremierichard** [comment]
thank you @VladislavFitz for your answer 🙂 

Do you have a roadmap to integrate such a feature in your `AlgoliaSearchClient` ?
Or should we keep the `InstantSearch` library ?

Thanks

**Comment by VladislavFitz** [comment]
We consider to integrate this feature into all our API clients in more efficient way in the coming months. Until then, you have to keep the InstantSearch. You can select just the `InstantSearchCore` framework while integrating the library into you project to reduce the size of dependency.
Stay tuned!

**Comment by VladislavFitz** [comment]
Hi @morgan-backmarket ,
Sorry for late reply. Unfortunately, this backend implementation of this feature has been postponed, so it might be implemented manually. I reopen this issue and it to the backlog. It will be added in the coming weeks.

**Comment by morgan-backmarket** [comment]
Hi @VladislavFitz 
Thank you for reopening this ticket 🙏 
We will work on this on our side as soon as it's available 👍

**Comment by VladislavFitz** [comment]
Hi @morgan-backmarket ,
The feature has been added in the [version 8.16](https://github.com/algolia/algoliasearch-client-swift/releases/tag/8.16.0). Let me know if something doesn't work as expected.

**Comment by morgan-backmarket** [comment]
> Hi @morgan-backmarket , The feature has been added in the [version 8.16](https://github.com/algolia/algoliasearch-client-swift/releases/tag/8.16.0). Let me know if something doesn't work as expected.

Great @VladislavFitz 🎉 i'll test this version as soon as possible and let you know. Thank you 🙏
