### ISSUE TITLE
Crash in tryLaunch / hostIterator

### ISSUE THREAD

**Issue by mxsc** [algolia/algoliasearch-client-swift#705]
**Describe the bug 🐛**
In our crash reports we can see a crash caused by AlgoliaSearchClient in HTTPRequest.swift in `tryLaunch` more concretely this line: `guard let host = hostIterator.next()` [https://github.com/algolia/algoliasearch-client-swift/blob/65d8343d043c1cd9b8a0d985f325dad75c3a6805/Sources/AlgoliaSearchClient/Transport/HTTP/HTTPRequest.swift#L77](here in the repository)

**To Reproduce 🔍**
SInce it is coming through the Appstore crash reports, we could not manage to reproduce it

**Expected behavior 💭**
Should not crash

**Screenshots 🖥**

**Environment:**
 iOS 14.2 iPhone XS

**Comment by VladislavFitz** [comment]
Hi @mxsc,
Thank you for reporting this. 
We will investigate it at the earliest opportunity.
Could you give more information about the frequency of this crash?

**Comment by mxsc** [comment]
For now we have a very small number of test users and it happened twice within one week.

**Comment by mxsc** [comment]
Maybe it is related but another crash happened in `retryableHosts` at this statement:

`hosts.resetExpired(expirationDelay: hostsExpirationDelay)`

in AlgoliaRetryStrategy.swift

**Comment by VladislavFitz** [comment]
Thank you for providing further details. I prioritise this issue and will keep you informed.

**Comment by VladislavFitz** [comment]
Hi @mxsc,
The crash has been fixed in the version 8.4.1.

**Comment by mxsc** [comment]
Thanks for the quick fix!
