### ISSUE TITLE
Proper Dictionary Syntax for Partial Update Object

### ISSUE THREAD

**Issue by rayfarer** [algolia/algoliasearch-client-swift#712]
Thanks again, @VladislavFitz for making it possible to partially update an object with a dictionary (see #651). However, could you perhaps offer some guidance on how to use this properly (and perhaps update [this page](https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/) with an example)?

In the past, I was able to use a [String:Any] dictionary to partially update an object (and I can still use this with say, updates to a Cloud Firestore document), but I am unfamiliar with this "PartialUpdate" type. I want to do something like this:

```
let updatedAlgoliaObject  = [
            "collection" : collection,
            "quantity" : quantity,
    ] as [String : Any]

index.partialUpdateObject(withID: objectID, with: updatedAlgoliaObject)
```

In this case, collection is a String and quantity is an Int. Getting the error message "Cannot convert value of type '[String : Any]' to expected argument type 'PartialUpdate'"

What I'm really asking is, how do I provide my own values to build a dictionary that will be accepted by partialUpdateObject? The only way I can get it to work now is to actually write in the values directly, like the example you provided in the 8.1 release:

```
index.partialUpdateObject(withID: "userAccountID", with: [
  "name": "John Doe",
  "postsCount": 2000,
  "followers": .add(value: "nightStranger51", unique: false),
  "followersCount": .increment(value: 20),
  "likes": .incrementSet(value: 15)
])
```

But I want to use variables. Can you please provide an example of how to get the partialUpdateObject to accept the dictionary I provided above?

**Comment by VladislavFitz** [comment]
Hi @rayfarer,

Thank you for your feedback. 

The purpose of `PartialUpdate` structure is to encapsulate all possible object update operations in the type safe way. 
The usage of `ExpressibleByLiteral` protocols such as `ExpressibleByStringLiteral` and `ExpressibleByBooleanLiteral` makes it possible to represent the update actions as literals makes and to store literal updates (such as `"postsCount": 2000`) and operations (such as `"followersCount": .increment(value: 20)`) in the same dictionary.

When you provide the literal values e.g. `["name": "John Doe", "postsCount": 2000]`, under the hood they are translated to operations `["name": .set(JSON("John Doe")), "postsCount": .set(JSON(2000))]`.

So if you want to use the external variables, the easiest solution is to wrap them into `.set(_ value: JSON)` operations constructors, 

```swift
let updatedAlgoliaObject  = [
  "collection" : .set(JSON(collection)),
  "quantity" : .set(JSON(quantity))
] as PartialUpdate
```

Then you can use this `PartialUpdate` object within `Index.partialUpdateObject` method. 
I hope this answers your question. 

For my part, I'll try to improve the developer experience of partialUpdate method by providing more straightforward API to use variables and will update the documentation accordingly.

**Comment by rayfarer** [comment]
Thank you so much, one again, for your quick and very helpful response! I appreciate the work you're doing!

**Comment by VladislavFitz** [comment]
I'm glad I was able to help 👌
