### ISSUE TITLE
Synonyms v2 integration

### ISSUE THREAD

**Issue by olance** [algolia/algoliasearch-client-swift#73]
Apparently the new Synonyms API hasn't been integrated in the Swift SDK?

**Comment by clement-leprovost** [comment]
So far, the Swift API client is considered a client-side implementation (just like the Android client), so the synonyms have been voluntarily left out (as well as other back-end only features).

*Note: If people start using Swift on the back-end, we may consider changing this policy—but for the time being I see no reason to do so.*
