### ISSUE TITLE
Bug: Index name missing from multiple indices search response

### ISSUE THREAD

**Issue by derek-cheung** [algolia/algoliasearch-client-swift#731]
**Describe the bug 🐛**
When performing a multiple indices search, the `indexName` field in `SearchResponse` is always nil. Performing the exact same search with the Android client returns the correct value for `indexName`.

Tested on v8.6

**Expected behavior 💭**
`indexName` value returned with `SearchResponse`

**Comment by VladislavFitz** [comment]
Hi @derek-cheung,
Thank you for reporting this. I check it and submit a patch by the end of this week.
