### ISSUE TITLE
Remove (unreleased) 8.8.0 tag

### ISSUE THREAD

**Issue by FelixHerrmann** [algolia/algoliasearch-client-swift#733]
**Describe the bug 🐛**
SPM uses 8.8.0 but it has a build error (availability checking missing for iOS in `Data+JSONString.swift`).

**To Reproduce 🔍**
1. File > Swift Packages > Update to Latest Package Versions

**Screenshots 🖥**
<img width="1512" alt="Bildschirmfoto 2021-03-01 um 17 05 22" src="https://user-images.githubusercontent.com/42500484/109524057-51320f00-7ab0-11eb-90f9-ce1fa0244ae8.png">

**Environment:**
 - OS: [iOS]
 - Version [8.8.0]

**Comment by VladislavFitz** [comment]
Hi @FelixHerrmann,
Could you try to re-add the package after clearing SPM caches? The tag was resubmitted manually yesterday and now this issue shouldn't occur.

**Comment by FelixHerrmann** [comment]
All good now, thank you!
