### ISSUE TITLE
Support returning JSON data as an alternative to Decodable

### ISSUE THREAD

**Issue by derek-cheung** [algolia/algoliasearch-client-swift#738]
Hi team,

Our apps are built using Kotlin Multiplatform and all our data models are defined in our shared code used across all platforms. Using the Android SDK, we are able to get data returned in JSON format which our shared code can then convert in to data models. However, because most of this SDK returns data conforming to Decodable, we would need to redefine all our data models on the iOS platform and convert them to JSON so our shared code can process it.

So far we have only been using the Search apis which do return json data so that has worked out fine but now we need to look at the Index apis. It would be great if the apis also exposed methods returning JSON data so it can be more flexible for use cases that require it.

**Comment by VladislavFitz** [comment]
Hi @derek-cheung ,

Could you give a concrete example of a method and the type you d'like to obtain? 
And what do you mean  by "JSON data" ? The `Data` type or the [`JSON`](https://github.com/algolia/algoliasearch-client-swift/blob/master/Sources/AlgoliaSearchClient/Models/Data%20structures/JSON.swift) type provided by Swift client?

**Comment by derek-cheung** [comment]
@VladislavFitz Thanks for the reply and apologies for the delay in responding. Normally I get email notifications for GH mentions but I never got one for this.

Specifically I'm looking at this method from the `Index` class

````
func getObject<T: Decodable>(
  withID objectID: ObjectID, 
  attributesToRetrieve: [Attribute] = [],
  requestOptions: RequestOptions? = nil,
  completion: @escaping ResultCallback<T>
) -> Operation & TransportTask
````

On the Kotlin side, the equivalent method is

````
public suspend fun <T : Indexable> getObject(
    serializer: KSerializer<T>,
    objectID: ObjectID,
    attributesToRetrieve: List<Attribute>? = null,
    requestOptions: RequestOptions? = null
): T
````

However, in Kotlin another method that returns just json data rather than a pre-defined object model is provided as an alternative option

````
public suspend fun getObject(
    objectID: ObjectID,
    attributesToRetrieve: List<Attribute>? = null,
    requestOptions: RequestOptions? = null
): JsonObject
````

It would be great for us if Swift could also do this, something like below. This will work for us as we're currently already using `public var hits: [Hit<JSON>]` from the `SearchResponse` class this way.

````
func getObject(
  withID objectID: ObjectID, 
  attributesToRetrieve: [Attribute] = [],
  requestOptions: RequestOptions? = nil,
  completion: @escaping ResultCallback<JSON>
) -> Operation & TransportTask
````

**Comment by VladislavFitz** [comment]
Hi @derek-cheung,

The `JSON` type provided by the Client conforms to `Codable` protocol, so you can use it with the `getObject` method as follows:

```swift
index.getObject(withID: "myId") { (result: Result<JSON, Error>) in
  if case .success(let responseJSON) = result {
    print("Response: \(responseJSON)")
  }
}
```

**Comment by derek-cheung** [comment]
@VladislavFitz Excellent, just tested this out and it does exactly what we we're looking. Thanks for your guidance on this issue!
