### ISSUE TITLE
iTunes connect submission issue

### ISSUE THREAD

**Issue by ehuynh** [algolia/algoliasearch-client-swift#75]
`Invalid Info.plist value. The value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/AlgoliaSearch.framework is invalid. The minimum value is 8.0`

It's currently not possible to submit an app that uses algoliasearch-client-swift via Carthage, because when the the framework is built via Carthage minimumosversion is set to 7.0, however it must be 8.0 or higher.

**Comment by clement-leprovost** [comment]
@ehuynh Should be fixed now on master HEAD. Please note that you will get compilation warnings about unnecessary checks; this is because the code itself is compatible with iOS 7.0, as requested in #62.
