### ISSUE TITLE
Algolia's use of custom operators clashes with custom operators defined in applications that consume this library

### ISSUE THREAD

**Issue by Killectro** [algolia/algoliasearch-client-swift#761]
**Describe the bug 🐛**
Algolia's use of custom operators (`>>>`) clashes with custom operators defined in applications, preventing applications that define their own versions of custom operators from compiling.

**To Reproduce 🔍**
1. Create a new project
2. Define a `>>>` operator in that project
3. Include `AlgoliaSearchClient` in that project
4. Attempt to use `>>>` operator
5. See compile the following compile error: `Ambiguous operator declarations found for operator`

**Expected behavior 💭**
Applications that use common custom operators such as `>>>` can compile their code while including Algolia library

**Additional context**
Swift's operator declaration statements [do not allow you](https://stackoverflow.com/a/27084631) to specify access control and therefore operator declarations are publicly visible by default. This means that if two different modules declare the same operator with different precedence the compile will be unable to resolve which operator to use.

Given that this is a Swift language limitation I think the Algolia library should avoid declaring custom operators that clash with operators likely to be defined in client applications such as `>>>`.

**Comment by VladislavFitz** [comment]
Hi @Killectro,

Thank you for reporting this issue. 
Could you provide more details about the reproduction steps: 
- The dependency manager you use in your project
- The code snippet triggering the compilation error

I tried to create a test Swift package using the Swift API client as a dependency via SPM and the declaration of the custom operator  `>>>` internally used in the API client haven't caused any issue.

Here is the code:

```swift
import AlgoliaSearchClient

public struct TestOperator {
  
    public init() {}
  
}

func >>> (lhs: TestOperator, rhs: TestOperator) -> TestOperator {
  return lhs
}

precedencegroup CustomPrecedence {
  lowerThan: DefaultPrecedence
  associativity: left
}

infix operator >>>: CustomPrecedence
```

And the test case:

```swift
import XCTest
@testable import TestOperator

final class TestOperatorTests: XCTestCase {
    func testExample() throws {
      let a = TestOperator()
      let b = TestOperator()
      let _ = a >>> b
    }
}
```

**Comment by Killectro** [comment]
Hey @VladislavFitz tacos for taking a look at this! I'm on my phone at the moment but I can sketch out our setup.

We have a module that holds our operator definition called Prelude. It defines the `>>>` infix operator itself as well as the definition of `>>>` as function composition ([seen here](https://github.com/pointfreeco/swift-prelude/blob/main/Sources/Prelude/Function.swift)). 

Then we have an application module that imports both Prelude and AlgoliaSearchClient and tried to compose two functions using the operator. We include Algolia via Cocoapods.

Hopefully that's enough to reproduce it!

**Comment by VladislavFitz** [comment]
Hi @Killectro,
Thank you for provided details. 
I created a [PR](https://github.com/algolia/algoliasearch-client-swift/pull/762) removing custom operator to build paths in the client. Not sure how the internal custom operator declaration leaks outside of the module, anyway it worth refactoring 🙂 
Could you test your project with `refactor/paths` branch to confirm that the issue is resolved?
