### ISSUE TITLE
Crash - AlgoliaSearchClient: protocol witness for Decodable.init(from:) in conformance JSON + 20

### ISSUE THREAD

**Issue by vishalgspaceo** [algolia/algoliasearch-client-swift#771]
**Describe the bug 🐛**
We found this crash in our current live app from Xcode Crash Logs

**Screenshots 🖥**
![Screenshot 2022-01-10 at 12 02 04 PM](https://user-images.githubusercontent.com/28976977/148726485-65dad388-cc4f-4c3e-888b-1b1ac55e42cf.png)
![Screenshot 2022-01-10 at 12 02 11 PM](https://user-images.githubusercontent.com/28976977/148726488-bfa3bd19-983f-45ed-8643-4c7833464460.png)
![Screenshot 2022-01-10 at 12 08 49 PM](https://user-images.githubusercontent.com/28976977/148726647-95508f1c-0226-4ffd-bec3-32d3fe3817d5.png)

**Environment:**
  - AlgoliaSearchClient (~> 8.13)
  - InstantSearch (~> 7.16)

**Additional context**
Kindly share me your email id to give full crash log about it.

**Comment by VladislavFitz** [comment]
Hi @vishalgspaceo,

Thank you for reporting this issue. 
Could you send the detailed crash log to vladislav.fitc@algolia.com ?

**Comment by vishalgspaceo** [comment]
> Hi @vishalgspaceo,
> 
> Thank you for reporting this issue. Could you send the detailed crash log to [vladislav.fitc@algolia.com](mailto:vladislav.fitc@algolia.com) ?

Sent email for that

**Comment by VladislavFitz** [comment]
This seems to be a non-systematic isolated issue, impossible to reproduce and no other complaints received.
