### ISSUE TITLE
Issue with query string containing & char

### ISSUE THREAD

**Issue by MKGitHub** [algolia/algoliasearch-client-swift#774]
**Describe the bug 🐛**
Hi, we are using a filter similar like this example
`.set(\.filters, to:"(test:\"Hello & World\")")`

But the query fails because it contains the & char. It is not encoded. This started with version 8.13.2, but worked before with and up to version 8.13.1.

Search / SearchesResponse, will fail with error.
`Error: Status code: 400 Message: Unknown parameter: 20World22`

Is this a bug in the SDK or do we need to do something since version 8.13.2?

**Expected behavior 💭**
It should encode all chars as needed.

**Environment:**
 - OS: iOS + macOS
 - Version 8.13.2

**Comment by VladislavFitz** [comment]
Hi @MKGitHub,
Thank you for reporting this. 
The fix will be released soon.
