### ISSUE TITLE
Facet values with certain characters don't work

### ISSUE THREAD

**Issue by mschinis** [algolia/algoliasearch-client-swift#789]
**Describe the bug 🐛**
I am currently using this library to build the requests sent to algolia, and noticed than when a value has a special character like `&` it is not percent encoded, leading to an incorrect query and the request failing.

If I percent encode it myself, before passing it in the library, the library then, double percent encodes it, leading to 0 results.

**Culprit**
https://github.com/algolia/algoliasearch-client-swift/blob/43c77cef8b2a6ceb5b1a328c33c8229ee0fdae4b/Sources/AlgoliaSearchClient/Models/Search/Query/Query%2BURLEncodable.swift#L105

**Expected behavior 💭**
The library should percent encode, allowing only alpha numerics instead of url allowed

**Comment by VladislavFitz** [comment]
Hi @mschinis,
Could you give a concrete example of a parameter leading to failure? 
I made a test of query with `&` and the url encoding works as expected.
```swift
let query = Query().set(\.query, to: "request with &")
print(query.urlEncodedString) // query=request%20with%20%26
```

**Comment by mschinis** [comment]
Hi @VladislavFitz,

Sure, the issue I'm having is for facet values. I should have mentioned that I'm also using InstantSearchCore for building these requests like so:

```swift
        let queryBuilder = QueryBuilder(
            query: "Ostrich wall lamp",
            disjunctiveFacets: [
                // ..
            ],
            filterGroups: [ 
                FilterGroup.And(
                    filters: [
                        FacetFilter(attribute: "manufacturer", stringValue: "&Quirky")
                    ],
                    name: "manufacturer"
                )
                // ...
            ],
            hierarchicalAttributes: [
                // ..
            ],
            hierachicalFilters: [
                // ..
            ]
        )
```

Executing the above query, results in the following:

<img width="1143" alt="Screenshot 2022-03-22 at 12 50 59" src="https://user-images.githubusercontent.com/771903/159465723-a68e6fc9-d443-434c-b39c-4fb51c946d47.png">


After looking at this further, might be related to how InstantSearchCore is using AlgoliaSearchClient 🤔
