### ISSUE TITLE
Client side error handling

### ISSUE THREAD

**Issue by tottakai** [algolia/algoliasearch-client-swift#790]
**Is your feature request related to a problem? Please describe 🙏**
When using the AlgoliaSearchClient we would like to determine the error case that the user faced and then inform them in the appropriate manner. But now we are not able to determine the type of errors because they are not available on the client side. So when we call `search` on an index and there is f.ex. no internet connection the HttpTransport.Error.noReachableHosts is thrown, but we cant match against that since it's not public. 

**Describe the solution you'd like 🤔**
Make the Error type usable on client code.

**Describe alternatives you've considered ✨**
Or convert the Error to a public error type if you don't want to expose that error.
 
**Additional context**
The errorDescription is just too long in some case, and too elaborate.

**Comment by agdavid** [comment]
Hi @VladislavFitz - Does the `merge` flag mean this has been addressed and merged into the latest client version already?
