### ISSUE TITLE
8.20.0 upgrade prevents project from building

### ISSUE THREAD

**Issue by squarefrog** [algolia/algoliasearch-client-swift#854]
**Describe the bug 🐛**
We use the `instantsearch-ios` 7.26.1  package in our app. About an hour ago we noticed our CI pipelines were failing with the following output:

```
❌  error: The package product 'AlgoliaSearchClient' requires minimum platform version 14.0 for the iOS platform, but this target supports 12.0 (in target 'InstantSearchCore' from project 'InstantSearch')
❌  error: The package product 'AlgoliaSearchClient' requires minimum platform version 14.0 for the iOS platform, but this target supports 12.0 (in target 'InstantSearch' from project 'InstantSearch')
❌  error: The package product 'AlgoliaSearchClient' requires minimum platform version 14.0 for the iOS platform, but this target supports 12.0 (in target 'InstantSearchInsights' from project 'InstantSearch')
```

After some digging, I can see [instant search package](https://github.com/algolia/instantsearch-ios/blob/master/Package.swift#L33-L35) references this package using the `from` rule, so it was naturally updated.

Our project has a minimum deployment target of iOS 15, so there should be no reason this change is a breaking one.

**To Reproduce 🔍**
1. Create a new Xcode project in Xcode 15, targeting iOS
2. Set the minimum deployment target to iOS 15
3. Add `https://github.com/algolia/instantsearch-ios` as a package dependency, with the rule set to `exact` and the version 7.26.1
4. Add all frameworks
5. Build

**Expected behavior 💭**
Package should build without failure for products targeting iOS 14 or above.

**Screenshots 🖥**

<img width="1512" alt="Screenshot 2024-02-02 at 15 20 13" src="https://github.com/algolia/algoliasearch-client-swift/assets/343450/64f96cd5-d5e8-4216-bcab-0d7f305cdfc4">

**Environment:**
 - OS: iOS
 - Version: 15.0
 - Swift Package Manager
 - Xcode 15.2

**Additional context**
Manually adding `algoliasearch-client-swift` with a locked version of 8.19.0 allows the project to build again, as this overrides the `from` rule locally

**Comment by squarefrog** [comment]
Actually, I think this is an issue with `instantsearch-ios` as the minimum target for that package is iOS 9. I would however argue bumping the minimum version is probably a major release rather than minor following semver rules.

**Comment by VladislavFitz** [comment]
Replied [here](https://github.com/algolia/instantsearch-ios/issues/305#issuecomment-1924250977)

**Comment by squarefrog** [comment]
I’ll close this as a duplicate on the parent package.

**Comment by Ma7m0udalaa** [comment]
Any update
