### ISSUE TITLE
Unknown parameter: explainModules

### ISSUE THREAD

**Issue by iludi95** [algolia/algoliasearch-client-swift#859]
Hello,

We are upgrading from InstantSearchClient 5.0 to AlgoliaSearchClient version 8.20.1, on iOS, and due of lackness of Explain Modules feature, in previous SDK, and documentation, we managed to make it work, setting a custom parameter up, on Query object. 

Now, seems it is available on new Codable data model and, could be set as `.set(\.explainModules, to: [.matchAlternatives])` on Query object but, when performing a request, backend responses with an status code of 400 with the next reason: "Unknown parameter: explainModules". We could made work it again setting it as custom parameter like so: `.set("explain": .string(ExplainModule.matchAlternatives.rawValue)])`.

Is an error with the CodingKey which should not be literally its name?

Thanks in advance

**Comment by Fluf22** [comment]
For future reference, if anyone is wondering: this API has been deprecated a year ago, it's not available anymore.
Consistency has been ensured, nothing should be breaking.
