### ISSUE TITLE
Missing product package

### ISSUE THREAD

**Issue by WilliamNumerade** [algolia/algoliasearch-client-swift#863]
**Describe the bug 🐛**
After pointing SPM to 9.0.0-beta.1 by using the commit hash, `Missing package product 'AlgoliaSearchClient'` error appears.
With previous version of 8.20.1, this did not occur.

**To Reproduce 🔍**
1. Open up the `xcodeproj` file
2. Project -> Package Dependencies
3. Change `AlgoliaSearchClient` to use `Commit` and paste in `443ed468d14dc7d6071a901e136212238ed8b006`
4. Confirm trying to run the app now results in above error message

To note, if I point to the 8.20.1 using the commit hash, the app builds and runs as expected.

**Expected behavior 💭**
App should compile and run as before

**Environment:**
 - OS: Mac 13.6.3
 - Xcode version 15.0.1

**Comment by salvatoreboemia** [comment]
Hi @WilliamNumerade have you solved? 

Thanks
