### ISSUE TITLE
Async await support

### ISSUE THREAD

**Issue by zarghol** [algolia/algoliasearch-client-swift#864]
**Is your feature request related to a problem? Please describe 🙏**
Is there any plan on having an async-await API ?

**Describe the solution you'd like 🤔**
As Swift 6 approach, and the Async Await being a first party approach to asynchronous code in the language, 
It could be interesting to have the SDK offering an API with these pattern.

 Example of translation : 
```swift
  @discardableResult func search(query: Query,
                                 requestOptions: RequestOptions? = nil,
                                 completion: @escaping ResultCallback<SearchResponse>) -> Operation & TransportTask
```
could be translated into 
```swift
  @discardableResult func search(query: Query,
                                 requestOptions: RequestOptions? = nil) async throws-> SearchResponse
```

**Describe alternatives you've considered ✨**
Letting the users build the APIs with extensions and continuations, but a first-party API could be better in terms of implementation (could be as deep as needed in the SDK), and the work could be done once instead of in multiple user teams.

**Additional context**
My team are currently implementing Async Await in our application, and it would be cool if the SDKs we use provide a API for it.

Thank you !

**Comment by Fluf22** [comment]
v9 finally supports async/await 🥳
