### ISSUE TITLE
What should I use instead of `InstantSearchCore.Logger.minSeverityLevel = .warning`?

### ISSUE THREAD

**Issue by qizh** [algolia/algoliasearch-client-swift#870]
https://github.com/algolia/algoliasearch-client-swift/blob/4322ab2dc8cdb7acb6d06a019fd56f84dc998f25/Sources/AlgoliaSearchClient/Helpers/Logging.swift#L29

This one is deprecated, which one to use then?
`8.21.0` is added when adding `InstantSearch` SPM

**Comment by qizh** [comment]
@Fluf22, so the only way to remove huge logs mess from the framework of the service I pay for is to every time add a log filter in the Xcode? 
**This is super incompetent.**

**Comment by qizh** [comment]
I will have to report this issue to Algolia official support.

**Comment by Fluf22** [comment]
@qizh Thank you for your feedback, opening a support request is actually a good way for us to see what our users want us to prioritise

We tried to match what is highlighted in the Apple documentation about logging ([documentation](https://developer.apple.com/documentation/os/logging/generating_log_messages_from_your_code), [customised level-debugging in XCode](https://www.swift.org/documentation/server/guides/libraries/log-levels.html), [customised log level programmatically](https://developer.apple.com/documentation/os/logging/customizing_logging_behavior_while_debugging), high-level [blog post](https://www.avanderlee.com/debugging/oslog-unified-logging/) that got out when the feature was introduced by Apple)

About the specific logs you sent, it seems they are outputted by the [InstantSearchInsights](https://github.com/algolia/instantsearch-ios/tree/master/Sources/InstantSearchInsights) package, so I would recommend opening an issue on this [repo](https://github.com/algolia/instantsearch-ios)
