### ISSUE TITLE
[bug]: Type PageMap<Item> does not conform to protocol

### ISSUE THREAD

**Issue by seanmiller802** [algolia/algoliasearch-client-swift#871]
### Description

I'm using macOS 15 and Xcode 16 and seeing this issue trying to build. It does work on Xcode 15 and macOS 14.5 though.

![PNG image](https://github.com/user-attachments/assets/d5fdf95c-8233-472c-bdba-4cd2c43f0074)

![PNG image](https://github.com/user-attachments/assets/668c522a-bb33-45b7-810d-c7d7ef1779f5)

### Client

Search

### Version

7.26.2

**Comment by Fluf22** [comment]
Hey @seanmiller802 👋🏻 
It looks like it may be something going on with InstantSearch, as I managed to create a new command-line project with AlgoliaSearchClient v8 on XCode 16.
Could you open an issue at https://github.com/algolia/instantsearch-ios, please?
Thanks!
