### ISSUE TITLE
[bug]: OpenAPI generated SearchClientConfiguration swift code missing public init making the API unusable

### ISSUE THREAD

**Issue by KaiOelfke** [algolia/algoliasearch-client-swift#872]
### Description

The code at https://github.com/algolia/algoliasearch-client-swift/blob/main/Sources/Search/SearchClientConfiguration.swift is generated. But the generator seems to have a bug as it's missing the public access control modifier for the initializer. So Algolia SDK users can't init this struct as the initialize is internal (default). So the SearchClientConfiguration API is not usable for SDK clients.

```swift
public struct SearchClientConfiguration: BaseConfiguration, Credentials {
    public let appID: String
    public var apiKey: String
    public var writeTimeout: TimeInterval
    public var readTimeout: TimeInterval
    public var logLevel: LogLevel
    public var defaultHeaders: [String: String]?
    public var hosts: [RetryableHost]
    public let compression: CompressionAlgorithm

    // Should be public
    init(
        appID: String,
        apiKey: String,
       // ...
    ) throws {  
       // ... 
    }
```

<img width="994" alt="Bildschirmfoto 2024-10-23 um 09 50 51" src="https://github.com/user-attachments/assets/e82a92e4-2ae7-496e-afe5-f6fc21af479c">

### Client

All

### Version

9.7.3

### Relevant log output

```shell
'SearchClientConfiguration' initializer is inaccessible due to 'internal' protection level
```

**Comment by Fluf22** [comment]
Thank you for the report @KaiOelfke!
