### ISSUE TITLE
Trouble Serializing Custom Objects From Search Response

### ISSUE THREAD

**Issue by Broich** [algolia/algoliasearch-client-swift#873]
Hello there,

I upgraded the Algolia Swift client to `9.9.1` and I'm having trouble understanding how I serialize response hits into my custom objects.

Previously, I was able to do something like this:

```Swift
index?.search(query: query) { [weak self] result in
    switch result {
    case .failure(let error):
        self?.logger.error("Error returning search results: \(error)")
    case .success(let response):
        do {
            let results: [MyLocalObject] = try response.extractHits()
            self?.results = results
            DispatchQueue.main.async {
                self?.tableView.reloadData()
            }
        } catch let error {
            self?.logger.error("error: \(error)")
        }
    }
}
```

But `extractHits` seems to be gone now and I couldn't find a place in the documentation that would explain if and what it was replaced by. 

I'm assuming I'm missing something super obvious.

Thanks for your help and support.

**Comment by Fluf22** [comment]
Hey @Broich 👋🏻 
With the new client, you can leverage generics:
```swift
import Foundation
import Core
import Search

let appID = "YOU_APP_ID"
let apiKey = "YOUR_API_KEY"
let indexName = "YOUR_INDEX_NAME"

struct MyLocalObject: Codable {
    let title: String
    let original_language: String
    let genres: [String]
}

let client = try SearchClient(appID: appID, apiKey: apiKey)

let res: SearchResponse<MyLocalObject> = try await client.searchSingleIndex(indexName: indexName)
dump(res.hits)

```

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/5dfd0432-f986-496b-b6b4-f3d827f46a7f">

> [!NOTE]
> Your struct must conform to the Codable protocol

**Comment by Broich** [comment]
Very helpful, thank you!
