### ISSUE TITLE
Strategy parameter not working

### ISSUE THREAD

**Issue by loryhuz** [algolia/algoliasearch-client-swift#88]
Hi,

I contacted support today about strategy parameter in multiple query, I didn't understand its behavior because it's actually not working as expected and documentation was wrong apparently.

It's should be passed as POST parameter. Here is the temp fix I did on my side:
https://github.com/algolia/algoliasearch-client-swift/pull/87

You can reproduce by setting the strategy to "stopIfEnoughMatches", if you reach the number of hits of the first query for example, you'll also get hits for other queries, so the parameter is not taken.

Thanks !

**Comment by clement-leprovost** [comment]
@loryhuz Good catch! The Swift implementation was actually in line with an erroneous version of our [REST API documentation](https://www.algolia.com/doc/rest#query-multiple-indexes), which has been corrected since. :)

**Comment by clement-leprovost** [comment]
Fixed in [version 3.4](https://github.com/algolia/algoliasearch-client-swift/releases/tag/3.4).
