### ISSUE TITLE
SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [algolia/algoliasearch-client-swift#91]
Hi,
With [Swift 3](https://swift.org/blog/swift-3-0-release-process/) it would also be nice to add support for [SwiftPM](https://swift.org/package-manager/)

Articles about **SwiftPM**:
* [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
* [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
* [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
* [Swift.org: Package Manager](https://goo.gl/E01ufX)

On your `README.md` add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top and add section for the installation with SwiftPM.

**Comment by clement-leprovost** [comment]
Definitely. I think it's too early right now because the Package Manager seems to be still in "early development" (as stated on their own website), but when Swift 3 is finally released it's probably something that we want to include support for (even if it's still in beta). => Added to the newly created v4 milestone.

**Comment by clement-leprovost** [comment]
The constraints currently imposed by the Swift PM do not play well with our project:

- All sources have to be in the same directory, or different modules will be produced!
- I can't see how to distinguish between the online and offline flavors as we are doing today with Cocoapods.

**Comment by AndrewSB** [comment]
@clement-leprovost can you go more into the "online and offline flavors" you're talking about? What is that?
Does Algolia host part of it's source code in a closed source framework, and then part of it open source in this repository?

**Comment by clement-leprovost** [comment]
@AndrewSB Yes; see the [Offline Mode documentation](https://www.algolia.com/doc/offline-mode). If you use only the online mode, then everything is open source *on the client side* (obviously, our servers are closed source...).

**Comment by bboralRMN** [comment]
Hello, one year after this ticket was opened, my team is starting to toy with server-side swift. Currently we will use REST API but a module would be nice when you decide this is doable.

**Comment by spinach** [comment]
Hi @bboralRMN, Thanks for the feedback! Indeed, this is something we should add support for. I will take a closer look at it in the coming weeks and will get back to you as soon as I have an update!

**Comment by spinach** [comment]
Sorry for the late implementation of that.

We just added support for SwiftPM! checkout the instructions in the [Install section](https://github.com/algolia/algoliasearch-client-swift#install). Let us know if you face any problems.
